### ISSUE TITLE
Not authorized for this request

### ISSUE THREAD

**Issue by mananaya** [IBM/watson-vehicle-damage-analyzer#47]
Am getting following error while trying to deploy using "Deploy to IBM Cloud" link. It is giving error that failed to create service wvda-visual-recognition. I have authorization to create standalone Watson Visual Recognition service, but when i use the "Deploy to IBM Cloud" it fails.

Preparing to start the job...
Logging into Bluemix as user: "####@##.ibm.com" 
Preparing the build artifacts...
Target: https://api.ng.bluemix.net
Creating service instance wvda-visual-recognition in org ####@##.ibm.com / space #### as ####@##.ibm.com...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: Failed to retrieve service details from catalog. Error : {"message":"Not authorized for this request.","code":403,"global_transaction_id":"gend-5113345195223265594"}

Finished: FAILED

**Comment by stevemart** [comment]
Can you confirm you are using a region that is not US South on IBM cloud?

**Comment by mananaya** [comment]
Hi Steve,
Am using US South on IBM Cloud. 


Thanks & regards,
Manas R Nayak,  ITIL® V3 Foundation, TOGAF® 9 Foundation
Mobile # +91-98305-17018
Office # +91-33-711-97008
E-mail - mananaya@in.ibm.com

**Comment by scottdangelo** [comment]
I am able to reproduce this issue. I believe it is due to breaking changes in the Visual Recognition API. I am working on a fix.

**Comment by scottdangelo** [comment]
This should work now. Please re-test.
