### ISSUE TITLE
Error deploying project from London location

### ISSUE THREAD

**Issue by gabicuesta** [IBM/watson-vehicle-damage-analyzer#63]
I'm trying to deploy your app on IBM Cloud using the deploy button but I have this error: Server error, status code: 502, error code: 10001, message: Service broker error: No matching deployments for the given plan_id.

Any idea of what I'm doing wrong? I'm deploying it from London.﻿

**Comment by scottdangelo** [comment]
@gabicuesta Can you please try deploying from US-South/Dallas ? It *appears* that the lite plan (which is free) is only available in that region, and that London will therefore not work .

**Comment by scottdangelo** [comment]
Update: The visual recognition *Only* exists in Dallas, so this code pattern will only work there.
