### ISSUE TITLE
Problems adding new pic categories to vehicleDamageAnalyzer

### ISSUE THREAD

**Issue by gabicuesta** [IBM/watson-vehicle-damage-analyzer#66]
How can I reset the vehicleDamageAnalyzer_xxxxxxx to update it with new pics?

I know how to add them to watson-visRec-setup file but I need to update the vehicleDamageAnalyzer.

Thanks,

**Comment by scottdangelo** [comment]
Do you mean you want to [update the classifer](https://console.bluemix.net/apidocs/visual-recognition?language=node#update-a-classifier) for the Visual Recognition services?
Or, once you've updated the classifier, you need to pick up the changes on your deployed server? (just restart the server)
Or something else?

**Comment by gabicuesta** [comment]
I'm new to this field, so sorry if I ask you very basic questions :)

I want to update the classifier.

To do it I have added another zip file to the data folder with some pics to try to allow the server to detect a new category of damage (paint damage). 

But when I add the zip and I add a new property on watson-visRec-setup the classifer isn't updated:
var createClassifierParams = {
        name: 'vehicleDamageAnalyzer',
        BrokenWindshield_positive_examples: fs.createReadStream('./data/BrokenWindshield.zip'),
        FlatTire_positive_examples: fs.createReadStream('./data/FlatTire.zip'),
        MotorcycleAccident_positive_examples: fs.createReadStream('./data/MotorcycleAccident.zip'),
        Vandalism_positive_examples: fs.createReadStream('./data/Vandalism.zip'),
        PaintDamage_positive_examples: fs.createReadStream('./data/PaintDamage.zip'),
        negative_examples: fs.createReadStream('./data/Negatives.zip')
      } 

I have restarted the server and it doesn't update it too.

What I'm doing wrong?

**Comment by scottdangelo** [comment]
See the link above for code to [update the classifier](https://console.bluemix.net/apidocs/visual-recognition?language=node#update-a-classifier).
Once you've run the code once, you've created it, so the only way to change it is to do an update.
You can also use curl to do a one-time update. If you put the update in your code, it will re-run each time the app is started.
